export const FETCHING = "FETCHING";
export const FETCHING_ERROR = "FETCHING_ERROR";
export const FETCHING_SUCCESS = "FETCHING_SUCCESS";
export const RESET_CONTEXT = "RESET_CONTEXT";
export const CAMBIAR_TIEMPO_DETALLE = "CAMBIAR_TIEMPO_DETALLE";
export const CAMBIAR_UNIDAD_TERMOMETRICA = "CAMBIAR_UNIDAD_TERMOMETRICA";
